CREATE TABLE dbo.RoleMaster
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    [CreatedDate] [datetime] NULL,
    CreatedBy int ,
    ModifiedDate datetime ,
    ModifiedBy int NULL,
    IsActive BIT NOT NULL DEFAULT(1)
);
 
GO
 
INSERT INTO RoleMaster( Name )
VALUES ('Admin'), ('Editor'), ('User');
 
GO
 
CREATE TABLE Employees
(
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Name NVARCHAR(300) NOT NULL ,
    Email NVARCHAR(300) Not Null Unique,
    Role INT FOREIGN KEY REFERENCES RoleMaster(Id),
    CreatedDate datetime NULL,
    CreatedBy int FOREIGN KEY REFERENCES Employees(Id),
    ModifiedDate datetime NULL,
    ModifiedBy int FOREIGN KEY REFERENCES Employees(Id),
    IsActive BIT NOT NULL DEFAULT(1)
);
 
GO
 
INSERT INTO Employees (Name, Email, Role, CreatedDate,CreatedBy,ModifiedDate, ModifiedBy, IsActive)
VALUES ('ABIR AIKATH','abiraikath@gmail.com',1,GETDATE(),1,GETDATE(),1,1),
('AAYUSHI GAMI','gamiaayushi@gmail.com',2,GETDATE(),1,GETDATE(),1,1),
('KARAN SINGH','karan.investica@gmail.com',2,GETDATE(),1,GETDATE(),1,1),
('SEJAL AGRE','sejal.investica@gmail.com',3,GETDATE(),1,GETDATE(),1,1),
('SHRUTIKA AGRE','shrutika.investica@gmail.com',3,GETDATE(),1,GETDATE(),1,1),
('SHUBHAM SALVE','investicaaccounts@gmail.com',3,GETDATE(),1,GETDATE(),1,1),
('SHUBHAM KANOJIYA','shubham.investica@gmail.com',3,GETDATE(),1,GETDATE(),1,1),
('RIDDHI DERE','riddhi14investica@gmail.com',3,GETDATE(),1,GETDATE(),1,1),
('SHITAL SHINDE','sital.investica@gmail.com',3,GETDATE(),1,GETDATE(),1,1);
 
GO
 
CREATE TABLE [dbo].[DocumentTable](
    [Id] [int] IDENTITY(1,1)  PRIMARY KEY NOT NULL,
    [Name] [varchar](300) NOT NULL,
    [Data] [varbinary] NOT NULL,
    [CreatedDate] [datetime] NULL,
    CreatedBy int   FOREIGN KEY REFERENCES Employees(Id) ,
    ModifiedDate datetime Null ,
    ModifiedBy int  FOREIGN KEY REFERENCES Employees(Id),
    [IsActive] [bit] NULL
);
 
GO
 
INSERT INTO dbo.DocumentTable (Name, Data, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, IsActive)
VALUES ('Dummy Document', 0x0102030405, GETDATE(), 1, GETDATE(), 1, 1);
 
GO
 
CREATE TABLE dbo.CompanyMaster
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Unikey NVARCHAR(200) NOT NULL UNIQUE,
    CompanyName NVARCHAR(500) NOT NULL,
    CreatedDate datetime NULL,
    CreatedBy int   FOREIGN KEY REFERENCES Employees(Id) ,
    ModifiedDate datetime Null ,
    ModifiedBy int  FOREIGN KEY REFERENCES Employees(Id),
    DocumentId INT FOREIGN KEY REFERENCES dbo.DocumentTable(Id),
    IsActive BIT NOT NULL DEFAULT(1)
);
 
GO
 
INSERT INTO dbo.CompanyMaster (Unikey, CompanyName, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, IsActive)
VALUES
('AANSWR_FASHION_PRIVATE_LIMITED_THE_PANT_PROJECT','AANSWR FASHION PRIVATE LIMITED (THE PANT PROJECT)',GETDATE(),1,GETDATE(),1,1),
('ACTOSERBA_ACTIVE_WHOLESALE_LTD','ACTOSERBA ACTIVE WHOLESALE LTD',GETDATE(),1,GETDATE(),1,1),
('ADIMAYA_SHAKTI_FRUIT_COMPANY','ADIMAYA SHAKTI FRUIT COMPANY',GETDATE(),1,GETDATE(),1,1),
('ASW_ENTERPRISES','ASW ENTERPRISES',GETDATE(),1,GETDATE(),1,1),
('BAGWAN_AND_SONS','BAGWAN AND SONS',GETDATE(),1,GETDATE(),1,1),
('BLISSCLUB_FITNESS_PVT_LTD','BLISSCLUB FITNESS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('BURMAN_HOSPITALITY_PVT_LTD','BURMAN HOSPITALITY PVT LTD',GETDATE(),1,GETDATE(),1,1),
('CAKEZONE_FOODTECH_PVT_LTD','CAKEZONE FOODTECH PVT LTD',GETDATE(),1,GETDATE(),1,1),
('CHIRAG_NEXT_BAR_AND_RESTAURANT','CHIRAG NEXT BAR AND RESTAURANT',GETDATE(),1,GETDATE(),1,1),
('COFFEE_CODES_INDIA_PVT_LTD','COFFEE CODES INDIA PVT LTD',GETDATE(),1,GETDATE(),1,1),
('COFFEE_DAY_GLOBAL_LIMITED','COFFEE DAY GLOBAL LIMITED',GETDATE(),1,GETDATE(),1,1),
('COFFEE_DAY_GLOBAL_LTD_VENDING','COFFEE DAY GLOBAL LTD-VENDING',GETDATE(),1,GETDATE(),1,1),
('COMMERCIAL_TRANSPORT','COMMERCIAL TRANSPORT',GETDATE(),1,GETDATE(),1,1),
('COMMERCIAL_TYRES_HUF','COMMERCIAL TYRES(HUF)',GETDATE(),1,GETDATE(),1,1),
('CUREFOODS_INDIA_LTD','CUREFOODS INDIA  LTD',GETDATE(),1,GETDATE(),1,1),
('ENRICH_HAIR_AND_SKIN_SOLUTIONS_PVT_LTD','ENRICH HAIR AND SKIN SOLUTIONS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('EVERSUB_INDIA_PVT_LTD','EVERSUB INDIA PVT LTD',GETDATE(),1,GETDATE(),1,1),
('FORTUNE_CHEMICALS_LTD','FORTUNE CHEMICALS LTD',GETDATE(),1,GETDATE(),1,1),
('FRAICHEUR_RETAIL_PRIVATE_LTD_NEWME','FRAICHEUR RETAIL PRIVATE LTD(NEWME)',GETDATE(),1,GETDATE(),1,1),
('GOURMET_INVESTMENTS_PVT_LTD','GOURMET INVESTMENTS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('HARI_OM_FOOD_MART','HARI OM FOOD MART',GETDATE(),1,GETDATE(),1,1),
('HOTEL_ABHIJEET','HOTEL ABHIJEET',GETDATE(),1,GETDATE(),1,1),
('HOTEL_AMRUT','HOTEL AMRUT',GETDATE(),1,GETDATE(),1,1),
('HOTEL_POORNIMA','HOTEL POORNIMA',GETDATE(),1,GETDATE(),1,1),
('HUNGER_PANGS_PVT_LTD','HUNGER PANGS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('JIMIS_BURGER_LLPJUICE_HAIR_MARKETING_PVT_LTD','JIMIS BURGER LLPJUICE HAIR MARKETING PVT LTD',GETDATE(),1,GETDATE(),1,1),
('KAAPI_MACHINES_INDIA_PVT_LTD','KAAPI MACHINES INDIA PVT LTD',GETDATE(),1,GETDATE(),1,1),
('KHAU_GAR_LLP','KHAU GAR LLP',GETDATE(),1,GETDATE(),1,1),
('MAVERIX_PLATFORMS_PVT_LTD','MAVERIX PLATFORMS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('MESS_JUICE_SALON','MESS (JUICE SALON)',GETDATE(),1,GETDATE(),1,1),
('MILA_STAR_RETAIL_PVT_LTD','MILA STAR RETAIL PVT LTD',GETDATE(),1,GETDATE(),1,1),
('NEKKANTI_MEGA_FOOD_PARK_PVT_LTD','NEKKANTI MEGA FOOD PARK PVT LTD',GETDATE(),1,GETDATE(),1,1),
('NEKKANTI_SEA_FOODS_LTD','NEKKANTI SEA FOODS LTD',GETDATE(),1,GETDATE(),1,1),
('JUICE_MARKETING_PVT_LTD','JUICE MARKETING PVT LTD',GETDATE(),1,GETDATE(),1,1),
('NUPA_TECHNOLOGIES_PVT_LTD','NUPA TECHNOLOGIES PVT LTD',GETDATE(),1,GETDATE(),1,1),
('OAM_INDUSTRIES_INDIA_PVT_LTD','OAM INDUSTRIES INDIA PVT LTD',GETDATE(),1,GETDATE(),1,1),
('PEEBLE_STREET_HOSPITALITY_PVT_LTD','PEEBLE STREET HOSPITALITY PVT LTD',GETDATE(),1,GETDATE(),1,1),
('POPSPACE_TECHNOLOGIES_PVT_LTD','POPSPACE TECHNOLOGIES PVT LTD',GETDATE(),1,GETDATE(),1,1),
('POPSPACE_TECHNOLOGIES_PVT_LTD_SEA_TURTLE','POPSPACE TECHNOLOGIES PVT LTD - SEA TURTLE',GETDATE(),1,GETDATE(),1,1),
('POPSPACE_TECHNOLOGIES_PVT_LTD_AANSWR_FASHION_PVT_LTD','POPSPACE TECHNOLOGIES PVT LTD-AANSWR FASHION PVT LTD',GETDATE(),1,GETDATE(),1,1),
('POPSPACE_TECHNOLOGIES_PVT_LTD_BOXSEAT_VENTURES_PVT_LTD_10_CLUB','POPSPACE TECHNOLOGIES PVT LTD-BOXSEAT VENTURES PVT LTD (10 CLUB)',GETDATE(),1,GETDATE(),1,1),
('POPSPACE_TECHNOLOGIES_PVT_LTD_FRAICHEUR_RETAIL_PVT_LTD','POPSPACE TECHNOLOGIES PVT LTD-FRAICHEUR RETAIL PVT LTD',GETDATE(),1,GETDATE(),1,1),
('POPSPACE_TECHNOLOGIES_PVT_LTD_STRIVE_CONSULTING','POPSPACE TECHNOLOGIES PVT LTD -STRIVE CONSULTING',GETDATE(),1,GETDATE(),1,1),
('PRATIK_LUNCH_HOME','PRATIK LUNCH HOME',GETDATE(),1,GETDATE(),1,1),
('PRIME_FRESH_LTD','PRIME FRESH LTD',GETDATE(),1,GETDATE(),1,1),
('PUREPLAY_SKIN_SCIENCES_INDIA_PVT_LTD','PUREPLAY SKIN SCIENCES (INDIA) PVT LTD',GETDATE(),1,GETDATE(),1,1),
('RASIKLAL_AND_COMPANY_PVT_LTD_SALIM_JAVED_AND_CO','RASIKLAL AND COMPANY PVT LTD, SALIM JAVED & CO',GETDATE(),1,GETDATE(),1,1),
('SANMAR_HOSPITALITY','SANMAR HOSPITALITY',GETDATE(),1,GETDATE(),1,1),
('SIDDHARTH_HOSPITALITY','SIDDHARTH HOSPITALITY',GETDATE(),1,GETDATE(),1,1),
('SRI_SRINIVASA_DAIRY_PRODUCTS_PRIVATE_LIMITED_CREAM_STONE','SRI SRINIVASA DAIRY PRODUCTS PRIVATE LIMITED (CREAM STONE TUB/ SCOOPS)',GETDATE(),1,GETDATE(),1,1),
('SUPERFRY_INDIA_PVT_LTD','SUPERFRY INDIA PVT LTD',GETDATE(),1,GETDATE(),1,1),
('TEXMEX_CUISINE_INDIA_PVT_LTD','TEXMEX CUISINE INDIA PVT LTD',GETDATE(),1,GETDATE(),1,1),
('TATA_STARBUCKS_PVT_LTD','TATA STARBUCKS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('VISHWA_LUNCH_HOME','VISHWA LUNCH HOME',GETDATE(),1,GETDATE(),1,1),
('WOW_MOMO_FOODS_PVT_LTD','WOW MOMO FOODS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('YUM_PLUM_PVT_LTD','YUM PLUM PVT LTD',GETDATE(),1,GETDATE(),1,1),
('TECHNO_SPORTSWEAR_PVT_LTD','TECHNO SPORTSWEAR PVT LTD',GETDATE(),1,GETDATE(),1,1),
('MASSIVE_RESTAURANTS_PVT_LTD','MASSIVE RESTAURANTS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('BLOOMBAY_ENTERPRISES_PVT_LTD','BLOOMBAY ENTERPRISES PVT LTD',GETDATE(),1,GETDATE(),1,1),
('DUAS_WORLD','DUA''S WORLD',GETDATE(),1,GETDATE(),1,1),
('MILLET_EXPRESS_FOODS_PRIVATE_LIMITED','MILLET EXPRESS FOODS PRIVATE LIMITED',GETDATE(),1,GETDATE(),1,1),
('JS_AROMA_VENTURE','JS AROMA VENTURE',GETDATE(),1,GETDATE(),1,1),
('ANITA_MOHAN_DODEJA','ANITA MOHAN DODEJA',GETDATE(),1,GETDATE(),1,1),
('THE_HEALING_WELLNESS_SPA','THE HEALING WELLNESS SPA',GETDATE(),1,GETDATE(),1,1),
('RIYAANA_CREATIONS_PVT_LTD','RIYAANA CREATIONS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('INDRAPRASTHA_ENTERPRISES','INDRAPRASTHA ENTERPRISES',GETDATE(),1,GETDATE(),1,1),
('SKY_LAYER_FARM_NUPA','SKY LAYER FARM (NUPA)',GETDATE(),1,GETDATE(),1,1),
('DTWELVE_ACCOMMODATIONS_PVT_LTD','DTWELVE ACCOMMODATIONS PVT LTD',GETDATE(),1,GETDATE(),1,1),
('BHAGWATI_STATIONERY_AND_XEROX','BHAGWATI STATIONERY AND XEROX',GETDATE(),1,GETDATE(),1,1),
('POPSPACE_TECHNOLOGIES_PVT_LTD_APOGEE_CONNECT_PVT_LTD','POPSPACE TECHNOLOGIES PVT LTD-APOGEE CONNECT PVT LTD',GETDATE(),1,GETDATE(),1,1),
('SHREE_NITYA_KARUNA_HOSPITALITY_PVT_LTD','SHREE NITYA KARUNA HOSPITALITY PVT LTD',GETDATE(),1,GETDATE(),1,1),
('SRI_MITRA_MARINE_AGENCIES','SRI MITRA MARINE AGENCIES',GETDATE(),1,GETDATE(),1,1),
('DTWELVE_SPACES_PRIVATE_LIMITED','DTWELVE SPACES PRIVATE LIMITED',GETDATE(),1,GETDATE(),1,1),
('BHARTI_OVERSEAS_PRIVATE_LIMITED','BHARTI OVERSEAS PRIVATE LIMITED',GETDATE(),1,GETDATE(),1,1),
('SUTRAHAUSPROJECT_LLP','SUTRAHAUSPROJECT LLP',GETDATE(),1,GETDATE(),1,1),
('BODHI_WELLNESS','BODHI WELLNESS',GETDATE(),1,GETDATE(),1,1);
 
GO
 
CREATE TABLE dbo.LicenseTypeMaster
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Unikey NVARCHAR(200) NOT NULL UNIQUE,
    AppTypeName NVARCHAR(300) NOT NULL,
    CreatedDate datetime NULL,
    CreatedBy int  FOREIGN KEY REFERENCES Employees(Id),
    ModifiedDate datetime NULL,
    ModifiedBy int  FOREIGN KEY REFERENCES Employees(Id),
    IsActive BIT NOT NULL DEFAULT(1),
);
 
GO
 
INSERT INTO dbo.LicenseTypeMaster (Unikey, AppTypeName, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, IsActive)
VALUES
('GMST_APP','GMST APP',GETDATE(),1,GETDATE(),1,1),
('GMST_RENEWAL','GMST RENEWAL',GETDATE(),1,GETDATE(),1,1),
('FSSAI_APP','FSSAI APP',GETDATE(),1,GETDATE(),1,1),
('FSSAI_RENEWAL','FSSAI RENEWAL',GETDATE(),1,GETDATE(),1,1),
('FSSAI_MODIFY','FSSAI MODIFY',GETDATE(),1,GETDATE(),1,1),
('TLC_APP','TLC APP',GETDATE(),1,GETDATE(),1,1),
('TLC_RENEWAL','TLC RENEWAL',GETDATE(),1,GETDATE(),1,1),
('HLC_APP','HLC APP',GETDATE(),1,GETDATE(),1,1),
('HLC_RENEWAL','HLC RENEWAL',GETDATE(),1,GETDATE(),1,1),
('FLC_APP','FLC APP',GETDATE(),1,GETDATE(),1,1),
('FLC_RENEWAL','FLC RENEWAL',GETDATE(),1,GETDATE(),1,1),
('SIGNAGE_APP','SIGNAGE APP',GETDATE(),1,GETDATE(),1,1),
('GMST_AMEND','GMST AMEND',GETDATE(),1,GETDATE(),1,1),
('SIGNAGE_RENEWAL','SIGNAGE RENEWAL',GETDATE(),1,GETDATE(),1,1),
('PANCHAYAT_NOC','PANCHAYAT NOC',GETDATE(),1,GETDATE(),1,1),
('PROFESSIONAL_TAX_REG','PROFESSIONAL TAX REG',GETDATE(),1,GETDATE(),1,1),
('EXCISE_RENEWAL','EXCISE RENEWAL',GETDATE(),1,GETDATE(),1,1),
('STORAGE_RENEWAL','STORAGE RENEWAL',GETDATE(),1,GETDATE(),1,1),
('SWM_CHARGES','SWM CHARGES',GETDATE(),1,GETDATE(),1,1),
('POLICE_LICENSE_RENEWAL','POLICE LICENSE RENEWAL',GETDATE(),1,GETDATE(),1,1),
('PCC_RENEWAL','PCC RENEWAL',GETDATE(),1,GETDATE(),1,1),
('SURRENDER_APP','SURRENDER APP',GETDATE(),1,GETDATE(),1,1),
('FSSAI_AMENDMENT','FSSAI AMENDMENT',GETDATE(),1,GETDATE(),1,1),
('PEC_PRC_SHOPS','PEC/PRC/SHOPS',GETDATE(),1,GETDATE(),1,1),
('FSSAI_ANNUAL_FILING','FSSAI ANNUAL FILING',GETDATE(),1,GETDATE(),1,1),
('GMST_SURRENDER','GMST SURRENDER',GETDATE(),1,GETDATE(),1,1),
('SUMMON_NOTICE','SUMMON NOTICE',GETDATE(),1,GETDATE(),1,1),
('FSSAI_INSPECTION_CLARIFICATION','FSSAI INSPECTION CLARIFICATION',GETDATE(),1,GETDATE(),1,1),
('FLC_SURRENDER','FLC SURRENDER',GETDATE(),1,GETDATE(),1,1),
('EXCISE_APP','EXCISE APP',GETDATE(),1,GETDATE(),1,1),
('GST_APP','GST APP',GETDATE(),1,GETDATE(),1,1),
('LEGAL_METROLOGY_APP','LEGAL METROLOGY APP',GETDATE(),1,GETDATE(),1,1),
('LEGAL_METROLOGY_AMENDMENT','LEGAL METROLOGY AMENDMENT',GETDATE(),1,GETDATE(),1,1),
('LEGAL_METROLOGY_NOTICE','LEGAL METROLOGY NOTICE',GETDATE(),1,GETDATE(),1,1),
('PPL_APP','PPL APP',GETDATE(),1,GETDATE(),1,1),
('PPL_RENEWAL','PPL RENEWAL',GETDATE(),1,GETDATE(),1,1),
('LWF_REG','LWF REG',GETDATE(),1,GETDATE(),1,1),
('PEC_APP','PEC APP',GETDATE(),1,GETDATE(),1,1),
('PACKAGING_EXTENSION','PACKAGING EXTENSION',GETDATE(),1,GETDATE(),1,1),
('PRC_PAYMENT','PRC PAYMENT',GETDATE(),1,GETDATE(),1,1),
('TP_RE_ISSUE','TP RE-ISSUE',GETDATE(),1,GETDATE(),1,1),
('POLLUTION_APP','POLLUTION APP',GETDATE(),1,GETDATE(),1,1),
('TLC_SURRENDER','TLC SURRENDER',GETDATE(),1,GETDATE(),1,1),
('PT_PAYMENT','PT PAYMENT',GETDATE(),1,GETDATE(),1,1),
('MEDICAL_FITNESS','MEDICAL FITNESS',GETDATE(),1,GETDATE(),1,1),
('EXCISE_FEE_PAYMENT','EXCISE FEE PAYMENT',GETDATE(),1,GETDATE(),1,1),
('SIGNAGE_SURRENDER_APP','SIGNAGE SURRENDER APP',GETDATE(),1,GETDATE(),1,1),
('PCC_APP','PCC APP',GETDATE(),1,GETDATE(),1,1),
('ARCHITECT_PLAN_SIGNATURE','ARCHITECT PLAN SIGNATURE',GETDATE(),1,GETDATE(),1,1),
('HEALTH_NOC','HEALTH NOC',GETDATE(),1,GETDATE(),1,1),
('SIGNAGE_SUMMON_NOTICE','SIGNAGE SUMMON NOTICE',GETDATE(),1,GETDATE(),1,1),
('PTRC_REG','PTRC REG',GETDATE(),1,GETDATE(),1,1),
('POLICE_LICENSE_APP','POLICE LICENSE APP',GETDATE(),1,GETDATE(),1,1),
('PT_EMPLOYER','PT EMPLOYER',GETDATE(),1,GETDATE(),1,1),
('GST_ABOP','GST ABOP',GETDATE(),1,GETDATE(),1,1),
('MONSOON_SHED_APP','MONSOON SHED APP',GETDATE(),1,GETDATE(),1,1),
('TLC_AND_SWM_FEES','TLC & SWM FEES',GETDATE(),1,GETDATE(),1,1),
('PROVISIONAL_FIRE_NOC','PROVISIONAL FIRE NOC',GETDATE(),1,GETDATE(),1,1),
('CLRA_APP','CLRA APP',GETDATE(),1,GETDATE(),1,1),
('FSSAI_MODIFICATION','FSSAI MODIFICATION',GETDATE(),1,GETDATE(),1,1),
('SANITARY_NOC','SANITARY NOC',GETDATE(),1,GETDATE(),1,1),
('PEC_PRC_SURRENDER','PEC/PRC SURRENDER',GETDATE(),1,GETDATE(),1,1),
('HLC_SURRENDER','HLC SURRENDER',GETDATE(),1,GETDATE(),1,1),
('FSSAI_SURRENDER','FSSAI SURRENDER',GETDATE(),1,GETDATE(),1,1),
('GST_MODIFICATION','GST MODIFICATION',GETDATE(),1,GETDATE(),1,1),
('INDEMNITY_AND_AFFIDAVIT','INDEMNITY AND AFFIDAVIT',GETDATE(),1,GETDATE(),1,1),
('FIRE_AFFIDAVIT','FIRE AFFIDAVIT',GETDATE(),1,GETDATE(),1,1),
('TLC_PENALTY','TLC PENALTY',GETDATE(),1,GETDATE(),1,1),
('HEALTH_CIC_APP','HEALTH CIC APP',GETDATE(),1,GETDATE(),1,1),
('TLC_NAME_CHANGE','TLC NAME CHANGE',GETDATE(),1,GETDATE(),1,1),
('EMPLOYER_REG','EMPLOYER REG',GETDATE(),1,GETDATE(),1,1),
('PRC_APP','PRC APP',GETDATE(),1,GETDATE(),1,1),
('SHEPORTAL_POSH','SHEPORTAL POSH',GETDATE(),1,GETDATE(),1,1),
('POSH_REG','POSH REG',GETDATE(),1,GETDATE(),1,1),
('PRINCIPAL_EMPLOYER_REG','PRINCIPAL EMPLOYER REG',GETDATE(),1,GETDATE(),1,1),
('EXCISE_NAME_CHANGE','EXCISE NAME CHANGE',GETDATE(),1,GETDATE(),1,1),
('SIGNAGE_DIFFERENCE_FEES','SIGNAGE DIFFERENCE FEES',GETDATE(),1,GETDATE(),1,1),
('SIGNAGE_AFFIDAVIT','SIGNAGE AFFIDAVIT',GETDATE(),1,GETDATE(),1,1),
('FORM_B','FORM B',GETDATE(),1,GETDATE(),1,1),
('PRADHAN_MANTRI_SCHEME','PRADHAN MANTRI SCHEME',GETDATE(),1,GETDATE(),1,1),
('FIRE_CIC_APP','FIRE CIC APP',GETDATE(),1,GETDATE(),1,1),
('RENEWED_SANITARY_NOC','RENEWED SANITARY NOC',GETDATE(),1,GETDATE(),1,1),
('PEC_PAYMENT','PEC PAYMENT',GETDATE(),1,GETDATE(),1,1),
('ELECTRIC_FITTING_CERT','ELECTRIC FITTING CERT',GETDATE(),1,GETDATE(),1,1),
('POSH_ANNUAL_RETURN','POSH ANNUAL RETURN',GETDATE(),1,GETDATE(),1,1),
('CHANGE_IN_USE','CHANGE IN USE',GETDATE(),1,GETDATE(),1,1),
('SIGNAGE_NAME_CHANGE','SIGNAGE NAME CHANGE',GETDATE(),1,GETDATE(),1,1);
 
GO
 
CREATE TABLE dbo.StatusMaster
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Unikey NVARCHAR(100) NOT NULL UNIQUE,
    StatusName NVARCHAR(200) NOT NULL,
    CreatedDate datetime NULL,
    CreatedBy int  FOREIGN KEY REFERENCES Employees(Id),
    ModifiedDate datetime NULL,
    ModifiedBy int  FOREIGN KEY REFERENCES Employees(Id),
    IsActive BIT NOT NULL DEFAULT(1)
);
 
GO
 
INSERT INTO dbo.StatusMaster (Unikey, StatusName, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, IsActive)
VALUES
('OBTAINED','OBTAINED',GETDATE(),1,GETDATE(),1,1),
('UNDER_PROCESS','UNDER PROCESS',GETDATE(),1,GETDATE(),1,1),
('REJECTED','REJECTED',GETDATE(),1,GETDATE(),1,1),
('CLOSED','CLOSED',GETDATE(),1,GETDATE(),1,1),
('DORMANT','DORMANT',GETDATE(),1,GETDATE(),1,1),
('REVERT_BACK','REVERT BACK',GETDATE(),1,GETDATE(),1,1);
 
GO
 
CREATE SEQUENCE TicketTrackingSeq
START WITH 1001
INCREMENT BY 1;
 
Go
 
CREATE TABLE Tickets
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CompanyId INT NOT NULL FOREIGN KEY REFERENCES CompanyMaster(Id),
    EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(Id),
    LicenseId INT NOT NULL FOREIGN KEY REFERENCES LicenseTypeMaster(Id),
    StatusId Int Not NULL FOREIGN KEY REFERENCES StatusMaster(Id),
    CompanyAddress NVARCHAR(1000) NOT NULL,
    Description NVARCHAR(MAX),
    TrackingNumber INT NOT NULL DEFAULT NEXT VALUE FOR TicketTrackingSeq,
    ValidTill DATETIME NULL,
    CreatedDate DATETIME  NULL DEFAULT GETDATE(),
    CreatedBy int  FOREIGN KEY REFERENCES Employees(Id),
    ModifiedDate DATETIME  NULL,
    ModifiedBy int  FOREIGN KEY REFERENCES Employees(Id),
);
 
GO
 
CREATE TABLE FontSheet
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CompanyId INT NULL FOREIGN KEY REFERENCES CompanyMaster(Id),
    EntityName NVARCHAR(500) NOT NULL,
    Address NVARCHAR(1000) NOT NULL,
    Phone NVARCHAR(20) NULL,
    Email NVARCHAR(300) NULL,
    PromoterNameAddress NVARCHAR(1000) NULL,
    EntityType NVARCHAR(300) NULL,
    NatureOfBusiness NVARCHAR(300) NULL,
    PanAadhar NVARCHAR(50) NULL,
    EntityPan NVARCHAR(50) NULL,
    DOB DATE NULL,
    Gender NVARCHAR(10) NULL,
    MaritalStatus NVARCHAR(50) NULL,
    FatherMotherSpouseName NVARCHAR(300) NULL,
    Area NVARCHAR(200) NULL,
    Ward NVARCHAR(200) NULL,
    Zone NVARCHAR(200) NULL,
    ProductServiceSold NVARCHAR(1000) NULL,
    ClientSource NVARCHAR(500) NULL,
    SourcedByEmpId INT NULL FOREIGN KEY REFERENCES Employees(Id),
    Comments NVARCHAR(MAX) NULL,
    Login NVARCHAR(200) NULL,
    Password NVARCHAR(500) NULL,  
    CreatedDate DATETIME  DEFAULT GETDATE(),
    CreatedBy INT  FOREIGN KEY REFERENCES Employees(Id),
    ModifiedDate DATETIME NULL,
    ModifiedBy INT  FOREIGN KEY REFERENCES Employees(Id),
    IsActive BIT NOT NULL DEFAULT(1)
);
 
GO
 
CREATE TABLE ShopCategoryLinks
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    StateName NVARCHAR(200) NOT NULL,
    Url NVARCHAR(1000) NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedDate DATETIME NULL DEFAULT GETDATE(),
    CreatedBy INT NULL FOREIGN KEY REFERENCES Employees(Id)
);
 
GO
 
INSERT INTO dbo.ShopCategoryLinks (StateName, Url, CreatedBy, IsActive)
VALUES ('MAHARASHTRA (MUMBAI)','https://portal.mcgm.gov.in/irj/portal/anonymous/qlsaeoService',1,1),
('REST OF MAHARASHTRA','https://maitri.mahsonline.gov.in/Login/Logni',1,1),
('KARNATAKA','http://164.100.133.176/ekarnika/Static/Home.aspx',1,1),
('DELHI','http://labourcis.nic.in/',1,1),
('MADHYA PRADESH','http://www.labour.mp.gov.in/Esr/public/Establishment_Apply.aspx',1,1),
('ANDHRA PRADESH','https://ineap.meeseva.gov.in/CitizenPortal/UserInterface/Citizen/CitizenHome',1,1),
('WEST BENGAL','https://wbshopsonline.gov.in/#',1,1),
('KERALA','https://cas.lc.kerala.gov.in/office/registration/onlinemain_online_pay.php',1,1),
('TAMIL NADU','https://labour.tn.gov.in/services/users/login',1,1),('GUJARAT','OFFLINE',1,1);
 
GO
 
CREATE TABLE dbo.TradeCategoryLinks
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CorporationName NVARCHAR(300) NOT NULL,
    Website NVARCHAR(1000) NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedDate DATETIME  DEFAULT GETDATE(),
    CreatedBy INT  FOREIGN KEY REFERENCES Employees(Id)
);
 
GO
 
INSERT INTO dbo.TradeCategoryLinks (CorporationName, Website, CreatedBy, IsActive)
VALUES ('NAVI MUMBAI MUNICIPAL CORPORATION','https://www.nmmc.gov.in/',1,1),
('THANE MUNICIPAL CORPORATION','https://thanecity.gov.in/tmc/CitizenHome.html',1,1),
('KALYAN-DOMBIVALI MUNICIPAL CORPORATION','https://kdmc.gov.in/kdmc/CitizenHome.html',1,1),
('MUMBAI MUNICIPAL CORPORATION','https://mcgm.gov.in/',1,1);
 
GO
 
CREATE TABLE Invoice
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    InvoiceNumber NVARCHAR(200) NOT NULL Unique,
    InvoiceTo  Nvarchar(300) Null,
    GstNoTo NVARCHAR (300) NOT NULL,
    InvoiceFrom Nvarchar(300) Null,
    GstNoFrom NVARCHAR (300) NOT NULL,
    Particulars Nvarchar(300) Null,
    GrossAmoutRs NVARCHAR(300) NOT NULL,
    NetAmoutRsm NVARCHAR(300) NOT NULL,
    SubTotal NVARCHAR(300) NOT NULL,
    IGST INT NOT NULL,
    NetTotal NVARCHAR(300) NOT NULL,
    CreatedDate DATETIME NULL DEFAULT GETDATE(),
    CreatedBy INT NULL FOREIGN KEY REFERENCES Employees(Id),
    ModifiedDate DATETIME NULL,
    ModifiedBy INT  FOREIGN KEY REFERENCES Employees(Id),
    IsActive BIT NOT NULL DEFAULT(1)
);



-- From here latest command is from 24-02-2026  this is the latest 


  Alter table Employees 
  Add Password Nvarchar(15) NULL;

Update Employees set Password = 'Jan@2026'
